apiVersion: v1
kind: Namespace
metadata:
  name: cnpg-system

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudnative-pg-controller-manager
  namespace: cnpg-system
  labels:
    app.kubernetes.io/name: cloudnative-pg
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: cloudnative-pg
  template:
    metadata:
      labels:
        app.kubernetes.io/name: cloudnative-pg
    spec:
      containers:
        - name: manager
          image: ghcr.io/cloudnative-pg/cloudnative-pg:1.23.0
          imagePullPolicy: IfNotPresent