apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: studytrack-db
  namespace: studytrack-dev
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:16.2
  storage:
    size: 100Mi
  bootstrap:
    initdb:
      database: studytrack-db-rw
      owner: devuser
      secret:
        name: db-secrets